version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://193.233.102.193:8000
    # IMAGE_PLACEHOLDER will be replaced by workflow with actual Docker Hub username
    image: IMAGE_PLACEHOLDER
    container_name: actionable-sentiment-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge