version: '3.8'

services:
  api:
    image: ghcr.io/sapsalevev/actionable-sentiment-backend/api:latest
    container_name: sentiment-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Database
      - DATABASE_URL=${DATABASE_URL:-sqlite+aiosqlite:///./database/bank_reviews.db}

      # Application
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

      # CORS - важно для продакшена
      - CORS_ORIGINS=${CORS_ORIGINS:-["http://193.233.102.193:3000"]}

    volumes:
      # Persistent database storage
      - ./database:/app/database

      # Logs
      - ./logs:/app/logs

    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - sentiment-network

    # Resource limits (опционально, раскомментируйте при необходимости)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: 1G
    #     reservations:
    #       cpus: '0.5'
    #       memory: 512M

networks:
  sentiment-network:
    driver: bridge

# Volumes для backup (опционально)
volumes:
  database-backup:
    driver: local
