version: '3.8'

services:
  api:
    # STAGING использует образ с тегом 'develop'
    image: ghcr.io/sapsalevev/actionable-sentiment-backend/api:develop
    container_name: sentiment-api-staging
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Database
      - DATABASE_URL=${DATABASE_URL:-sqlite+aiosqlite:///./database/bank_reviews.db}

      # Application - STAGING environment
      - ENVIRONMENT=${ENVIRONMENT:-staging}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}

      # CORS - настроен для staging сервера
      - CORS_ORIGINS=${CORS_ORIGINS:-["http://89.23.99.74:3000","http://localhost:3000"]}

    volumes:
      # Persistent database storage
      - ./database:/app/database

      # Logs
      - ./logs:/app/logs

    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - sentiment-network-staging

    # Resource limits для staging (можно ограничить меньше чем production)
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  sentiment-network-staging:
    driver: bridge

# Volumes для backup (опционально)
volumes:
  database-backup:
    driver: local
